server:
  port: 8001

mybatis:
  check-config-location: true
  #config-location: classpath:mybatis/mybatis.cfg.xml
  #非当前module
  type-aliases-package: com.wh.api.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
  #这个名字很重要，对外暴露微服务的名字
    name: springcloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud1
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

