server:
  port: 8002


feign:
  hystrix:
    enabled: true

spring:
  application:
    #这个名字很重要，对外暴露微服务的名字
    name: springcloud-dept-consumer

# ribbon 依赖eureka client.ribbon 让消费方从服务注册中心获知有哪些地址可用.(ribbon从这些地址中选择一个合适的服务器)。
eureka:
  client: #客户端注册到eureka服务列表中
    service-url:
        #defaultZone: http://localhost:7001/eureka/
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false