server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client: #客户端注册到eureka服务列表中
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: wh-springcloud1
  company.name: www.atguigu.com
  build.artifactId: $artifactId$
  build.version: $project.version$


zuul:
  routes:
    mydept.serviceId: springcloud-dept
    mydept.path: /mydept/**
  # 忽略的service
  ignored-services: springcloud-dept
  prefix: /wh